<?php
$labels = array();
$labels['folder_info_message'] = 'Nachricht über dem Ordner';
$labels['folder_info_htmleditor'] = 'HTML-Editor einschalten';
$labels['trash_message'] = 'Nachrichten, die länger als {} Tage im Papierkorb gespeichert sind, werden automatisch gelöscht.';
$labels['junk_message'] = 'Nachrichten, die länger als {} Tage im Spam gespeichert sind, werden automatisch gelöscht.';
?>
