<?php
$labels = array();
$labels['folder_info_message'] = 'Message au-dessus du dossier';
$labels['folder_info_htmleditor'] = 'Activer l\'éditeur HTML';
$labels['trash_message'] = 'Les messages stockés dans la corbeille depuis plus de {} jours seront automatiquement supprimés.';
$labels['junk_message'] = 'Les messages stockés dans les spams depuis plus de {} jours seront automatiquement supprimés.';
?>
